#set_location_assignment PIN_C14 -to SD[2]
#set_location_assignment PIN_D14 -to SD[5]
#set_location_assignment PIN_D11 -to SD[4]
#set_location_assignment PIN_A13 -to SD[15]
#set_location_assignment PIN_B13 -to SD[14]
#set_location_assignment PIN_A14 -to SD[13]
#set_location_assignment PIN_B14 -to SD[12]
#set_location_assignment PIN_E11 -to SD[1]
#set_location_assignment PIN_A12 -to A_A[13]
#set_location_assignment PIN_B12 -to A_A[14]
#set_location_assignment PIN_A11 -to A_A[11]
#set_location_assignment PIN_B11 -to A_A[12]
#set_location_assignment PIN_C11 -to SD[3]
#set_location_assignment PIN_F9 -to TRG_IN
#set_location_assignment PIN_A15 -to SD[11]
#set_location_assignment PIN_A10 -to I/O_A[0]
#set_location_assignment PIN_C9 -to SD[6]
#set_location_assignment PIN_D9 -to CE_A
#set_location_assignment PIN_A9 -to I/O_A[2]
#set_location_assignment PIN_B9 -to I/O_A[1]
#set_location_assignment PIN_N3 -to I/O_B[4]
#set_location_assignment PIN_P3 -to I/O_B[5]
#set_location_assignment PIN_R3 -to A_B[13]
#set_location_assignment PIN_T3 -to A_B[12]
#set_location_assignment PIN_T2 -to A_B[14]
#set_location_assignment PIN_R4 -to A_B[11]
#set_location_assignment PIN_T4 -to CE_B
#set_location_assignment PIN_M6 -to WE_B
#set_location_assignment PIN_P6 -to A_B[10]
#set_location_assignment PIN_M7 -to I/O_B[7]
#set_location_assignment PIN_R5 -to I/O_B[0]
#set_location_assignment PIN_T5 -to I/O_B[1]
#set_location_assignment PIN_R6 -to I/O_B[2]
#set_location_assignment PIN_T6 -to I/O_B[3]
#set_location_assignment PIN_L7 -to I/O_B[6]
#set_location_assignment PIN_R7 -to I/O_B[12]
#set_location_assignment PIN_T7 -to I/O_B[13]
#set_location_assignment PIN_L8 -to A_B[6]
#set_location_assignment PIN_M8 -to A_B[8]
#set_location_assignment PIN_N8 -to A_B[9]
#set_location_assignment PIN_P8 -to A_B[7]
#set_location_assignment PIN_R8 -to I/O_B[14]
#set_location_assignment PIN_T8 -to I/O_B[15]
set_location_assignment PIN_N13 -to FD[15]
#set_location_assignment PIN_M12 -to FPGA_TXD
set_location_assignment PIN_N14 -to FD[6]
set_location_assignment PIN_P15 -to FLAGA
set_location_assignment PIN_P16 -to FD[7]
set_location_assignment PIN_R16 -to FLAGB
#set_location_assignment PIN_K11 -to TEST_PORT3
set_location_assignment PIN_N16 -to FD[4]
set_location_assignment PIN_N15 -to FD[5]
set_location_assignment PIN_L14 -to SLWR
set_location_assignment PIN_L13 -to SLRD
set_location_assignment PIN_L16 -to FD[0]
set_location_assignment PIN_L15 -to FD[1]
set_location_assignment PIN_K16 -to FD[2]
set_location_assignment PIN_K15 -to FD[3]
#set_location_assignment PIN_J16 -to NCS
set_location_assignment PIN_J15 -to NRESET
#set_location_assignment PIN_J14 -to SD[7]
#set_location_assignment PIN_J12 -to TRG_OUT
#set_location_assignment PIN_J13 -to NWR
set_location_assignment PIN_M16 -to CLKOUT
set_location_assignment PIN_M15 -to usb_ifclk
#set_location_assignment PIN_D4 -to A_A[7]
#set_location_assignment PIN_B1 -to I/O_A[13]
#set_location_assignment PIN_C2 -to I/O_A[11]
#set_location_assignment PIN_C1 -to ASDO
#set_location_assignment PIN_F3 -to I/O_A[10]
#set_location_assignment PIN_D2 -to NCSO
#set_location_assignment PIN_D1 -to I/O_A[9]
#set_location_assignment PIN_F4 -to NSTATUS
#set_location_assignment PIN_F2 -to A_A[3]
#set_location_assignment PIN_F1 -to A_A[4]
#set_location_assignment PIN_G2 -to A_A[5]
#set_location_assignment PIN_G1 -to A_A[6]
#set_location_assignment PIN_H1 -to DCLK
#set_location_assignment PIN_H2 -to DATA_CONF
#set_location_assignment PIN_H5 -to NCONFIG
#set_location_assignment PIN_H4 -to TDI 
#set_location_assignment PIN_H3 -to TCK
#set_location_assignment PIN_J5 -to TMS
#set_location_assignment PIN_J4 -to TDO
#set_location_assignment PIN_J3 -to NCE
#set_location_assignment PIN_E1 -to I/O_A[8]
set_location_assignment PIN_E16 -to CLK_OSC
#set_location_assignment PIN_E15 -to NRD
#set_location_assignment PIN_H14 -to CONF_DONE
#set_location_assignment PIN_H13 -to MSEL0
#set_location_assignment PIN_H12 -to MSEL1
#set_location_assignment PIN_G12 -to MSEL2
#set_location_assignment PIN_G16 -to INIT_DONE
#set_location_assignment PIN_G15 -to CRC_ERROR
#set_location_assignment PIN_B16 -to SD[10]
#set_location_assignment PIN_F14 -to SD[0]
#set_location_assignment PIN_D16 -to INT
#set_location_assignment PIN_D15 -to CMD
#set_location_assignment PIN_C16 -to SD[8]
#set_location_assignment PIN_C15 -to SD[9]
#set_location_assignment PIN_A8 -to I/O_A[4]
#set_location_assignment PIN_B8 -to I/O_A[3]
#set_location_assignment PIN_C8 -to I/O_A[7]
#set_location_assignment PIN_E8 -to TEST_PORT4
#set_location_assignment PIN_F8 -to TEST_PORT2
#set_location_assignment PIN_A7 -to I/O_A[5]
#set_location_assignment PIN_B7 -to I/O_A[6]
#set_location_assignment PIN_C6 -to A_A[10]
#set_location_assignment PIN_A6 -to I/O_A[12]
#set_location_assignment PIN_B6 -to I/O_A[14]
#set_location_assignment PIN_E6 -to TEST_PORT1
#set_location_assignment PIN_A5 -to I/O_A[15]
#set_location_assignment PIN_A2 -to A_A[0]
#set_location_assignment PIN_B5 -to LB_A
##set_location_assignment PIN_A4 -to UB_A
#set_location_assignment PIN_B4 -to OE_A
#set_location_assignment PIN_D5 -to A_A[9]
#set_location_assignment PIN_D6 -to WE_A
#set_location_assignment PIN_A3 -to A_A[2]
#set_location_assignment PIN_B3 -to A_A[1]
#set_location_assignment PIN_C3 -to A_A[8]
#set_location_assignment PIN_M1 -to SCK2//LED6
set_location_assignment PIN_J2 -to TURBIO1
set_location_assignment PIN_J1 -to CNV1
set_location_assignment PIN_K2 -to SCK1
set_location_assignment PIN_K1 -to DATA1
set_location_assignment PIN_L2 -to CNV2
set_location_assignment PIN_L1 -to TURBIO2
set_location_assignment PIN_L3 -to LED1
set_location_assignment PIN_N2 -to LED3
set_location_assignment PIN_N1 -to DATA2
set_location_assignment PIN_L4 -to LED2
set_location_assignment PIN_P2 -to LED5
set_location_assignment PIN_P1 -to LED4
set_location_assignment PIN_R1 -to SCK2
#set_location_assignment PIN_R9 -to OE_B
#set_location_assignment PIN_T9 -to UB_B
#set_location_assignment PIN_K9 -to A_B[5]
#set_location_assignment PIN_L9 -to A_B[4]
#set_location_assignment PIN_M9 -to A_B[3]
#set_location_assignment PIN_N9 -to I/O_B[8]
set_location_assignment PIN_R10 -to FD[12]
#set_location_assignment PIN_T10 -to A_B[2]
set_location_assignment PIN_R11 -to FD[10]
set_location_assignment PIN_T11 -to FD[11]
set_location_assignment PIN_R12 -to FD[8]
set_location_assignment PIN_T12 -to FD[9]
#set_location_assignment PIN_K10 -to I/O_B[9]
#set_location_assignment PIN_L10 -to I/O_B[10]
#set_location_assignment PIN_P9 -to LB_B
#set_location_assignment PIN_P11 -to A_B[0]
set_location_assignment PIN_R13 -to PKTEND
set_location_assignment PIN_T13 -to SLCS
#set_location_assignment PIN_M10 -to I/O_B[11]
#set_location_assignment PIN_N11 -to A_B[1]
set_location_assignment PIN_T14 -to FIFOADR1
set_location_assignment PIN_T15 -to FLAGC
set_location_assignment PIN_R14 -to FIFOADR0
set_location_assignment PIN_P14 -to SLOE
#set_location_assignment PIN_L11 -to FPGA_RXD
set_location_assignment PIN_M11 -to FD[13]
set_location_assignment PIN_N12 -to FD[14]
